### ISSUE TITLE
[BUG] - nit pick - fix achievibit url in README.md

### ISSUE THREAD

**Issue by ortichon** [Kibibit/achievibit#16]
when adding Achievibit to another repo and trying to add Achievibit's url as a webhook, I get to following error:
`this doesn't look like a valid URL`
it can be fixed by prefixing the url with `http://` 

sorry about this uber-minor nit pick.

**Comment by Thatkookooguy** [comment]
@ortichon  go ahead and fix this through github. this way you'll get the new achievement 😉

**Comment by ortichon** [comment]
didn't get any 😞
