### ISSUE TITLE
[ACHIEVEMENT] IM THE DEVIL I LIKE METAL

### ISSUE THREAD

**Issue by Thatkookooguy** [Kibibit/achievibit#166]
similar to Optimus Prime, this achievement is given when a pull request id is only made out of at least 2 '6':

So:
id: 6 won't get the achievement

But 66, 666, and so on, will.

please write unit tests for this achievement. Unit tests are located in [the test folder](https://github.com/Kibibit/achievibit/tree/develop/test) and should cover isSequenceOfSixes(number) and getting the achievement. should cover both success and failure scenarios (look at other files for examples)

 achievement image names should be camelCase of the achievement name.

## Reference
It's a Tenacious D reference to the movie The Pick of Destiny. Usually, the metadata is as follows:

name: the name of the achievement. Usually a quote or word-play on a pop-culture reference
short: additional pop-culture one-liner
description: mainly tells the user why he got the achievement. It should be informative but can also contain fun references :-)

So here, I would suggest the following (to be in line with the Tenacious D references):

name: I'm the devil I love metal

image: https://goo.gl/images/vy384p 

short: There's two option I'm suggesting: either the quote of the next line in the song: "Check this riff, it's fucking tasty" or the quote the devil says at the start of the song: "I AM COMPLETE!"

description:
```
your pull request id (<id_number>) summoned the devil himself!

I hope that code you submitted was a masterpiece, or you're gonna gargle mayonnaise
```

Thses are only suggestions. If you have a better name, short, or description, go ahead :-)

**Comment by gideonla** [comment]
No problem :)

**Comment by puneet97** [comment]
> But 66, 666, and so on, will.
Based on the conditions you mentioned 166, 266 and so on would also get the achievement IIUC.

**Comment by Thatkookooguy** [comment]
@puneet97 maybe I didn't write it as clearly, but I wrote that it is made **only out of 6s**.
So it's made only out of 2 or more 6s :-)

**Comment by andrearosr** [comment]
Can I take this?

**Comment by Thatkookooguy** [comment]
@andrearosr sure, go ahead! I updated the description to give a bit more details.

If you have any questions don't hesitate to ask :-)

**Comment by Thatkookooguy** [comment]
@andrearosr This one already has a PR submitted for it. But we'll be happy to see a PR from you.

If you want you can suggest a new achievement or I can create an issue with a specific one.

Tell me if you do and I'll create one

**Comment by Thatkookooguy** [comment]
@andrearosr Although if you'll submit another PR for this achievement with unit tests already written, I'll accept your change :-)

**Comment by andrearosr** [comment]
@Thatkookooguy oh I should've checked the open PRs for that, I just assumed no one had worked on that because this issue is not referenced. @gideonla are you still interested in completing the PR with the requested changes? I can just pick another achievement for now

**Comment by gideonla** [comment]
Hi, @andrearosr thanks for asking. Yes, I am still working on it. I hope to push a new PR in a few days.

**Comment by Thatkookooguy** [comment]
This achievement is open PRs again. If anyone want to work on this, go ahead :-)
