### ISSUE TITLE
Issue with biWinning.achievement

### ISSUE THREAD

**Issue by dunaevsky** [Kibibit/achievibit#44]
It gives the achievement even if you only have 1 commit without anything in it. Makes it really easy to achieve,

Should consider making it for at least 2 commits in a PR maybe,

Not sure if this is a bug, but wanted to communicate this issue.

**Comment by Thatkookooguy** [comment]
It's a bug right now. If you don't have any status checks on commits, you get the achievement.

That's why it is too easy. I'll fix it to ignore this achievements if you didn't implement any status checks for commits

@dunaevsky good find!

**Comment by dunaevsky** [comment]
So we'll leave it open for now?

**Comment by ortichon** [comment]
@dunaevsky if you create a PR that states something like:
resolves #<issueNumber>
it automatically close the issue when the PR is merged. 
so yes, this issue will stay open for now.

**Comment by Thatkookooguy** [comment]
I just fixed this issue.

you can see my PR entry above my comment here, which I connected to this issue just like @ortichon said

**Comment by dunaevsky** [comment]
@ortichon I know I did an achievement about it 🥇
